version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: master_org_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MASTER_DB_HOST=db
      - MASTER_DB_PORT=5432
      - MASTER_DB_NAME=master_org_db
      - MASTER_DB_USER=postgres
      - MASTER_DB_PASSWORD=postgres
      - SECRET_KEY=your-super-secret-key-change-this-in-production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data: